name: PyLS-Spyder tests

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    linux:
        name: Linux Py${{ matrix.PYTHON_VERSION }}
        runs-on: ubuntu-latest
        env:
            PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
            RUNNER_OS: "ubuntu"
        strategy:
            fail-fast: false
            matrix:
                PYTHON_VERSION: ["3.6", "3.7", "3.8"]
        steps:
            - name: Checkout branch/PR
              uses: actions/checkout@v1
            - name: Install Conda
              uses: conda-incubator/setup-miniconda@v2
              with:
                activate-environment: test
                auto-update-conda: true
                auto-activate-base: false
                python-version: ${{ matrix.PYTHON_VERSION }}
            - name: Install build/test dependencies
              shell: bash -l {0}
              run: pip install python-lsp-server[all] pytest pytest-cov coverage mock
            - name: Run tests
              shell: bash -l {0}
              run: pytest -v -x --cov=pyls_spyder pyls_spyder/tests
